# Generated by Django 3.1.7 on 2021-03-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclass', '0001_initial'),
        ('account', '0002_auto_20210227_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolclass.schoolclass'),
        ),
    ]
