# Generated by Django 3.1.7 on 2021-05-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_wx_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(blank=True, default=None, max_length=192, null=True, verbose_name='微信openid'),
        ),
    ]
