# Generated by Django 3.1.7 on 2021-05-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210520_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wx_avatar_url',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='微信头像url'),
        ),
    ]
