# Generated by Django 3.1.7 on 2021-05-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_wx_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wx_password',
            field=models.CharField(blank=True, default=None, max_length=192, null=True, verbose_name='微信密码'),
        ),
    ]
