# Generated by Django 3.1.7 on 2021-05-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_wx_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wx_stuff',
            field=models.IntegerField(default=0, verbose_name='微信权限'),
        ),
    ]
