# Generated by Django 3.1.7 on 2021-03-02 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='班级名')),
                ('year', models.CharField(choices=[('2020——2021学年', '2020——2021学年'), ('2021——2022学年', '2021——2022学年'), ('2022——2023学年', '2022——2023学年'), ('2023——2024学年', '2023——2024学年'), ('2024——2025学年', '2024——2025学年'), ('2025——2026学年', '2025——2026学年')], default='2020—2021', max_length=30, verbose_name='学年')),
                ('semester', models.CharField(choices=[('第一学期', '第一学期'), ('第二学期', '第二学期')], default=1, max_length=20, verbose_name='学期')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='班级人数')),
                ('tercher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '班级',
            },
        ),
    ]
