# Generated by Django 3.1.7 on 2021-03-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='semester',
            field=models.CharField(choices=[('第一学期', '第一学期'), ('第二学期', '第二学期')], default='第二学期', max_length=20, verbose_name='学期'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='year',
            field=models.CharField(choices=[('2020——2021学年', '2020——2021学年'), ('2021——2022学年', '2021——2022学年'), ('2022——2023学年', '2022——2023学年'), ('2023——2024学年', '2023——2024学年'), ('2024——2025学年', '2024——2025学年'), ('2025——2026学年', '2025——2026学年')], default='2020——2021学年', max_length=30, verbose_name='学年'),
        ),
    ]
