# Generated by Django 3.1.7 on 2021-03-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status_memory',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status_test',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status_time',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(-3, 'Submitted'), (-2, 'In queue'), (-1, 'Running'), (0, 'Accepted'), (1, 'Partial score'), (2, 'Compilation error'), (3, 'System error')], db_index=True, default=-3),
        ),
    ]
