# Generated by Django 3.1.7 on 2021-03-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20210303_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='running_process',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
