# Generated by Django 3.1.7 on 2021-03-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_running_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='running_process',
            field=models.CharField(blank=True, default='', max_length=192),
        ),
    ]
