# Generated by Django 3.1.7 on 2021-03-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20210303_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='running_process',
            field=models.CharField(blank=True, max_length=192),
        ),
    ]
