# Generated by Django 3.1.7 on 2021-03-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20210307_1750'),
        ('submission', '0006_auto_20210303_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.contest'),
        ),
    ]
