# Generated by Django 3.1.7 on 2021-03-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_type',
            field=models.IntegerField(choices=[(0, '测试'), (1, '作业')], default=0, max_length=30, verbose_name='类型'),
        ),
    ]
