# Generated by Django 3.1.7 on 2021-03-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20210306_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestproblem',
            name='weight',
        ),
    ]
