# Generated by Django 3.1.7 on 2021-03-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_remove_contestproblem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='invitation_code',
            field=models.CharField(default='123456', max_length=192, verbose_name='邀请码'),
        ),
    ]
