# Generated by Django 3.1.7 on 2021-03-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_contest_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='invitation_code',
            field=models.CharField(default='123456', max_length=192, verbose_name='邀请码(当比赛的访问控制为「受邀请时」使用)'),
        ),
    ]
