# Generated by Django 3.1.7 on 2021-03-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20210307_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_time_score',
            field=models.BooleanField(default=False, verbose_name='得分是否随时间衰减'),
        ),
    ]
