# Generated by Django 3.1.7 on 2021-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_contest_is_time_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='access_level',
            field=models.PositiveIntegerField(choices=[(0, '仅管理员可见'), (10, '受邀请'), (20, '公开')], default=0, verbose_name='访问控制'),
        ),
    ]
