# Generated by Django 3.1.7 on 2021-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_contest_time_score_wait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='time_score_wait',
            field=models.IntegerField(default=20, verbose_name='多长时间后分数衰减（分钟）'),
        ),
    ]
