# Generated by Django 3.1.7 on 2021-05-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20210520_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-pk'], 'verbose_name_plural': '测试'},
        ),
        migrations.AlterModelOptions(
            name='contestparticipant',
            options={'ordering': ('-is_confirmed', '-score'), 'verbose_name_plural': '测试_用户'},
        ),
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ['identifier'], 'verbose_name_plural': '测试_问题'},
        ),
    ]
