# Generated by Django 3.1.7 on 2021-05-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_contestproblem_problem_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ['id'], 'verbose_name_plural': '测试_问题'},
        ),
        migrations.AddField(
            model_name='contest',
            name='standings',
            field=models.TextField(blank=True, default=None, verbose_name='榜单'),
        ),
    ]
