# Generated by Django 3.1.7 on 2021-05-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_contest_visualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='standings',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='榜单'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='visualization',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='可视化分析'),
        ),
    ]
