# Generated by Django 3.1.7 on 2021-03-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='名字')),
                ('ip', models.CharField(max_length=30, verbose_name='IP')),
                ('port', models.IntegerField(verbose_name='端口号')),
                ('token', models.CharField(max_length=192, verbose_name='密钥')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('enabled', models.BooleanField(default=False)),
                ('concurrency', models.PositiveIntegerField(default=1, verbose_name='并发量')),
                ('master', models.BooleanField(default=True, verbose_name='主节点')),
            ],
            options={
                'verbose_name_plural': '判题服务器',
                'ordering': ['add_time'],
            },
        ),
    ]
