# Generated by Django 3.1.7 on 2021-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20210301_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('查询类', '查询类'), ('更新类', '更新类'), ('创建视图类', '创建视图类'), ('创建基本表', '创建基本表')], default='查询类', max_length=20, verbose_name='题目类型'),
        ),
    ]
