# Generated by Django 3.1.7 on 2021-05-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pk'], 'verbose_name_plural': '帖子'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk'], 'verbose_name_plural': '评论'},
        ),
    ]
