# Generated by Django 3.1.7 on 2021-05-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20210521_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='images_count',
            field=models.IntegerField(default=0, verbose_name='图片数量'),
        ),
    ]
