# Generated by Django 3.1.7 on 2021-05-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210523_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_small_comment',
            field=models.IntegerField(default=0, verbose_name='面向小评论'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(max_length=148, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
    ]
